[build]
  command = "node netlify-build.js"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "10.2.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
